ViTParams:
  num_channels: 3
  image_size: 224
  patch_size: 16

  hidden_size: 768
  num_blocks: 12
  num_heads: 12
  dropout: 0.0
  mlp_size: 3072
  num_classes: 1000

TrainerParams:
  n_iter: 310
  lr: 0.0005
  weight_decay: 0.065

  label_smoothing: 0.1