ViTParams:
  num_channels: 3
  image_size: 224
  patch_size: 32

  hidden_size: 384
  num_blocks: 12
  num_heads: 6
  dropout: 0.0
  mlp_size: 1536
  num_classes: 1000

TrainerParams:
  n_iter: 300
  lr: 0.001
  weight_decay: 0.03